// ==UserScript==
// @name        .ru destroyer
// @description This script helps you with browsing the internet
// @author       546pvp
// @version      0.1.0
// @license      MIT
// @match        *://*.ru/*
// ==/UserScript==
var blockedDomains = ['ik-ptz.ru', 'proonline.ru', 'fantasticfilms.ru', 'tanterm.ru', 'leonardogift.ru']
var hostname = location.host
console.warn(hostname)
 if(blockedDomains.includes(hostname)) {
    document.write(`
    <h1 align='center' style="font-family:'Helvetica'">Website ${hostname} can be malicious</h1>
    <p align='center' style="font-family:'Helvetica'">This message was autogenerated because you opened '.ru' domain</p>
    <footer><p id='credit' align='left' style="font-family:'Helvetica'">Script by <a href='https://greasyfork.org/users/741384-546pvp'>546pvp</p></footer>
    `)
}
